version: 2
updates:
  # Node.js dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    reviewers:
      - 'your-username'
    assignees:
      - 'your-username'

  # Python dependencies for API
  - package-ecosystem: 'pip'
    directory: '/apps/api-python'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'

  # Docker dependencies
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 2
    commit-message:
      prefix: 'chore(docker)'

  # GitHub Actions dependencies
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 2
    commit-message:
      prefix: 'chore(actions)'
