services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

# Removed db service as SQLite is file-based and does not require a container

volumes:
  sqlite_data:
