name: DFS Platform - Performance & Monitoring

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'DFSForge/**'
      - 'dfs-system-2/**'

jobs:
  performance-tests:
    name: '📊 Performance & Load Testing'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          npm install -g pnpm playwright
          pnpm install
          pip install locust pytest-benchmark

      - name: Install Playwright browsers
        run: playwright install

      - name: Run frontend performance tests
        run: |
          pnpm run test:performance
          pnpm run lighthouse:ci

      - name: Run backend load tests
        run: |
          cd dfs-system-2
          python -m pytest tests/performance/ --benchmark-json=benchmark.json
          locust -f tests/load/locustfile.py --headless -u 100 -r 10 -t 60s --host http://localhost:8000

      - name: Upload performance reports
        uses: actions/upload-artifact@v3
        with:
          name: performance-reports
          path: |
            lighthouse-results/
            benchmark.json
            locust-reports/

  dependency-updates:
    name: '🔄 Automated Dependency Management'
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update Node.js dependencies
        run: |
          npm install -g pnpm npm-check-updates
          ncu -u
          pnpm install
          pnpm run test:quick

      - name: Update Python dependencies
        run: |
          pip install pip-tools
          cd dfs-system-2
          pip-compile --upgrade requirements.in
          pip install -r requirements.txt
          python -m pytest tests/unit/ -x

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: automated dependency updates'
          title: '🤖 Automated Dependency Updates'
          body: |
            ## Automated Dependency Updates

            This PR contains automated updates to project dependencies:

            ### Node.js Dependencies
            - Updated package.json and pnpm-lock.yaml
            - All tests passing ✅

            ### Python Dependencies
            - Updated requirements.txt
            - All unit tests passing ✅

            **Auto-generated by GitHub Actions**
          branch: automated/dependency-updates
